# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01002da799d5596b7b003f0c0734fd6df679424ffc82c62f2477ce12de399e6842d82c530f164b8a53a9afca3a84537663ec50af2724e33d2cf4a575f1bd4d8

test:
  secret_key_base: e8cc84bd1d519cbaa90f6e95541c35a16828a80b9c02b017dbe65b6175668cf3685fb5729b33afe4a21b9fd4fe3639909d530e22b4b6cf3eacabe1f825330602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
